# configuration file for projet_osint

theHarvester :
  enabled : True   # True or False to enable or Disable the tool
dnscan :
  enabled :
shodan :
  enabled :
  api_key :
urlscan.io :
  enabled :
  api_key :
